version: "3.5"
services:
    database:
        container_name: ${APPLICATION_NAME}-db
        image: mysql:${MYSQL_VERSION}
        command: mysqld --sql_mode="" --max_allowed_packet="524288000" --wait_timeout="100"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
            - "MYSQL_DATABASE=${APPLICATION_NAME}"
            - "MYSQL_PASSWORD="
            - "MYSQL_USER=root"
            - "TZ=America/Sao_Paulo"
        ports:
            - ${MYSQL_LOCAL_PORT}:3306
    app:
        container_name: ${APPLICATION_NAME}-app
        build:
            context: ./containers/application
        working_dir: /var/www/html
        tty: true
        volumes:
            - ${APPLICATION_PATH}:/var/www/html
        ports:
            - ${WEBSERVER_LOCAL_PORT}:80
            - 3000:3000
        depends_on:
            - database
volumes:
    dbdata: